BEGIN TRANSACTION;

DROP TABLE IF EXISTS PRODUTOS;

CREATE TABLE PRODUTOS (
    PRODUTO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PRODUTO_NOME TEXT NOT NULL,
    PRODUTO_VALORUNIT REAL NOT NULL,
    PRODUTO_PRATELEIRAS_ID INTEGER NOT NULL
);

DROP TABLE IF EXISTS PRATELEIRAS;

CREATE TABLE PRATELEIRAS (
    PRATELEIRA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PRATELEIRA_NOME TEXT NOT NULL,
    PRATELEIRA_LOCAL TEXT NOT NULL

);

DROP TABLE IF EXISTS NOTAS;

CREATE TABLE NOTAS (
    NOTA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOTA_DATA DATE NOT NULL,
    NOTA_NUM INTEGER NOT NULL,
    NOTA_CLIENTES_ID INTEGER NOT NULL,
    NOTA_ATENDENTES_ID INTEGER NOT NULL

);

DROP TABLE IF EXISTS ITENSNOTA;

CREATE TABLE ITENSNOTA (
    ITEMNOTA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ITEMNOTA_NUMNOTA INTEGER NOT NULL,
    ITEMNOTA_PRODUTOS_ID INTEGER NOT NULL,
    ITEMNOTA_QTDE REAL NOT NULL,
    ITEMNOTA_VALORUNIT REAL,
    ITEMNOTA_VALORTOTAL REAL 


);

DROP TABLE IF EXISTS ATENDENTES;

CREATE TABLE ATENDENTES (
    ATENDENTE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ATENDENTE_NOME TEXT NOT NULL
    
);
DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE CLIENTES (
	CLIENTE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CLIENTE_NOME TEXT NOT NULL,
	CLIENTE_CPF TEXT NOT NULL,
	CLIENTE_TELEFONE TEXT NOT NULL,
	CLIENTE_TOTALCOMPRAS REAL,
	CLIENTE_CIDADES_ID INTEGER,
	CONSTRAINT CLIENTES_FK FOREIGN KEY (CLIENTE_CIDADES_ID) REFERENCES CIDADES(CIDADES_ID) ON DELETE RESTRICT
);


DROP TABLE IF EXISTS CIDADES;

CREATE TABLE CIDADES (
	CIDADES_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CIDADE_NOME TEXT,
	CIDADE_CEP TEXT NOT NULL
);

COMMIT;