


-- RESULTS_SETS RETORNA PRATELEIRAS E NOME DO LOCAL
-- SELECT PRATELEIRA_NOME, PRATELEIRA_LOCAL FROM PRATELEIRAS;


-- RESULTS_SETS PRODUTOS ORDENADOS POR PRATELEIRAS
-- SELECT 
--     PRATELEIRA_NOME,
--     PRODUTO_NOME,
--     PRODUTO_VALORUNIT
-- FROM PRATELEIRAS, PRODUTOS
-- WHERE PRATELEIRAS.PRATELEIRA_ID = PRODUTOS.PRODUTO_PRATELEIRAS_ID
-- ORDER BY PRATELEIRA_NOME


-- RESULTS_SETS 1 CUPOM FISCAL COMPLETO, LISTANDO CAMPOS DE DIVERSAS TABELAS
-- SELECT 
--     NOTA_DATA,
--     NOTA_NUM,
--     PRODUTO_NOME,
--     PRODUTO_VALORUNIT,
--     CLIENTE_NOME
-- FROM ITENSNOTA, NOTAS, PRODUTOS, CLIENTES
-- WHERE ITENSNOTA.ITEMNOTA_NUMNOTA = NOTAS.NOTA_NUM 
-- AND ITENSNOTA.ITEMNOTA_PRODUTOS_ID = PRODUTOS.PRODUTO_ID
-- AND NOTAS.NOTA_NUM = 1010
-- AND CLIENTES.CLIENTE_ID = NOTAS.NOTA_CLIENTES_ID;


-- RESULTS_SETS CLIENTES (TODOS OS CAMPOS)
-- SELECT * FROM CLIENTES;


-- RESULTS_SETS ATENDENTES (TODOS OS CAMPOS)
-- SELECT * FROM ATENDENTES;






