BEGIN TRANSACTION;
DROP TABLE IF EXISTS CIDADES;
CREATE TABLE CIDADES(
    CIDADE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CIDADE_NOME TEXT NOT NULL
);

DROP TABLE IF EXISTS PESSOAS;
CREATE TABLE PESSOAS(
    PESSOA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PESSOA_NOME TEXT NOT NULL,
    PESSOA_IDADE INTEGER NOT NULL,
    PESSOA_CIDADES_ID INTEGER NOT NULL
);

INSERT INTO CIDADES(CIDADE_NOME)
    VALUES
    ('Florianopolis'),
    ('Campo Grande'),
    ('Blumenau'),
    ('Sao Joao Batista');

INSERT INTO PESSOAS(PESSOA_NOME, PESSOA_IDADE, PESSOA_CIDADES_ID)
    VALUES
    ('Gabriel Mello', 18, 4),
    ('Adriano Machado', 47, 2),
    ('Felipe Luiz', 30, 1),
    ('Luiz Calo', 50, 3),
    ('Pedro Lucas', 13, 1),
    ('Pedro Lucas', 18, 2),
    ('Arnaldo Sarce', 18, 3);

COMMIT;

SELECT * FROM CIDADES;

SELECT * FROM PESSOAS;